before:
  hooks:
    - go mod tidy
builds:
  - id: kubectl-rook-ceph
    ldflags: -s -w
    main: ./cmd
    binary: kubectl-rook_ceph
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - builds:
      - kubectl-rook-ceph
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE
