#!/usr/bin/env bash

_kubect_rook_ceph_completions()
{
    local cur prev opts
    COMPREPLY=() # An array variable from which bash reads the possible completions generated by a completion function.
    cur="${COMP_WORDS[COMP_CWORD]}"  # An array variable consisting of the individual words in the current command line, ${COMP_LINE}.
    prev="${COMP_WORDS[COMP_CWORD-1]}" # An previous index into ${COMP_WORDS} of the word containing the current cursor position.
    opts="ceph rook rbd mon-endpoints operator --help --namespace"
    NAMESPACE="rook-ceph"

    if [[ ${cur} == * ]] ; then
        # shellcheck disable=SC2207
        COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
        cur="${COMP_WORDS[COMP_CWORD]}"
        if [[ ${prev} == "rook" ]]; then
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "status version" -- "${cur}") )
        elif [[ ${prev} == "--namespace" ]]; then
            namespace="$(kubectl get ns| awk '{print $1}'| tail -n +2)"
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "restart ${namespace}" -- "${cur}") )
        elif [[ ${prev} == "operator" ]]; then
            # Todo to read custom namespace
            # operator_cm_key store all the key of rook-ceph-operator-config configmap
            operator_cm_key="$(kubectl --namespace "$NAMESPACE" get configmaps rook-ceph-operator-config -o json | jq --monochrome-output '.data' | awk '{print $1}' | sed 's/[^_[:alnum:]]//g')"
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "restart ${operator_cm_key}" -- "${cur}") )
        fi
    fi
    return 0
}

complete -F _kubect_rook_ceph_completions rook-ceph
