name: Cluster Setup
description: Cluster setup for plugin test
inputs:
  github-token:
    description: GITHUB_TOKEN from the calling workflow
    required: true
  op-ns:
    description: operator namespace where rook operator will deploy
    required: false
  cluster-ns:
    description: cluster namespace where ceph cluster will deploy
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Minikube
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        tests/github-action-helper.sh install_minikube_with_none_driver v1.33.3

    - name: print k8s cluster status
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system

    - name: use local disk
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        tests/github-action-helper.sh use_local_disk
        tests/github-action-helper.sh create_partitions_for_osds


    - name: deploy rook cluster
      shell: bash --noprofile --norc -eo pipefail -x {0}
      if: inputs.op-ns == 'rook-ceph' || inputs.cluster-ns == 'rook-ceph'
      run: tests/github-action-helper.sh deploy_rook

    - name: deploy rook cluster in custom namespace
      shell: bash --noprofile --norc -eo pipefail -x {0}
      if: inputs.op-ns != 'rook-ceph' || inputs.cluster-ns != 'rook-ceph'
      run: tests/github-action-helper.sh deploy_rook_in_custom_namespace ${{ inputs.op-ns }} ${{ inputs.cluster-ns }}
